### ISSUE TITLE
Old fashioned CMD interface

### ISSUE THREAD

**Issue by kushkapadia** [kushkapadia/servitect#7]
The current command-line interface (CLI) feels outdated and could benefit from modernisation.

Enhancements could include:

1. **Improved User Experience**: Introducing features like autocomplete, syntax highlighting, and a more user-friendly layout to enhance usability.

2. **Customizable Themes:** Allowing users to change the color scheme and font style for a more personalized experience.

<img width="760" alt="image" src="https://github.com/user-attachments/assets/8c528c78-3b18-4867-8ec0-0d3583250d12">

**Comment by SimpleCyber** [comment]
Hii @kushkapadia can u assign this issue to me ?

**Comment by kushkapadia** [comment]
> Hii @kushkapadia can u assign this issue to me ?

Hey, yes sure!

**Comment by kushkapadia** [comment]
Our goal is to provide some CMD interface like vite or nextjs.
Do checkout some ready made npm packages for our use case.

We can discuss here, if theres anything.

**Comment by SimpleCyber** [comment]
Hii , I have modified the CMD interface please have the look on it

**Comment by Mitshah2406** [comment]
The code has some major issues: 

The dependencies installed doesn't work with commonJS.
The code for the main functions is deleted in your commit which is causing the code to crash.
